// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:analytics_plugin_firebase/plugin_firebase.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZpgwnoAO0gC84g5Osp4NCUbAi5ufzefk',
    appId: '1:451641862977:web:561222a42c69e106b08fc0',
    messagingSenderId: '451641862977',
    projectId: 'charagan-57eb9',
    authDomain: 'charagan-57eb9.firebaseapp.com',
    storageBucket: 'charagan-57eb9.appspot.com',
    measurementId: 'G-HX36HL8B0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMcPb5EONqpXT0OcgDcaO1bFbA5rV5O80',
    appId: '1:451641862977:android:af53db43ed386720b08fc0',
    messagingSenderId: '451641862977',
    projectId: 'charagan-57eb9',
    storageBucket: 'charagan-57eb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZNuIwFEaSCtGKp81h9Eyn_qxbJYMvjmU',
    appId: '1:451641862977:ios:4c0575ec2d39e092b08fc0',
    messagingSenderId: '451641862977',
    projectId: 'charagan-57eb9',
    storageBucket: 'charagan-57eb9.appspot.com',
    iosClientId:
        '451641862977-iussojnd5mtrd0216bocqqftask592ob.apps.googleusercontent.com',
    iosBundleId: 'com.segment.analyticsExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZNuIwFEaSCtGKp81h9Eyn_qxbJYMvjmU',
    appId: '1:451641862977:ios:4c0575ec2d39e092b08fc0',
    messagingSenderId: '451641862977',
    projectId: 'charagan-57eb9',
    storageBucket: 'charagan-57eb9.appspot.com',
    iosClientId:
        '451641862977-iussojnd5mtrd0216bocqqftask592ob.apps.googleusercontent.com',
    iosBundleId: 'com.segment.analyticsExample',
  );
}
